name: co-dsc
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6.4
  - numpy=1.14.0
  - pandas=0.22.0
  - pandasql=0.7.3
  - requests=2.18.4
  - matplotlib=2.1.2  
  - scikit-image=0.13.1
  - scikit-learn=0.19.1
  - scipy=1.0.0
  - seaborn=0.8.1  
  - statsmodels=0.8.0
  - shapely==1.6.2
  - pip:
    - geojson==2.3.0
    - geopy==1.12.0
    - gmaps==0.7.4
    - googlemaps==2.5.1
    - pyshp==1.2.12
    - tables==3.4.2
    - utm==0.4.2
    

